apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: coubee-be-user 
                  uri: http://coubee-be-user-service:8080
                  predicates:
                    - Path=/api/user/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-store
                  uri: http://coubee-be-store-service:8080
                  predicates:
                    - Path=/api/store/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-product
                  uri: http://coubee-be-product-service:8080
                  predicates:
                    - Path=/api/product/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-order
                  uri: http://coubee-be-order-service:8080
                  predicates:
                    - Path=/api/orders/**
                  filters:
                    - addAuthenticationHeader