apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: coubee-be-user 
                  uri: http://coubee-be-user-service:8080
                  predicates:
                    - Path=/api/user/**
                  filters:
                    - addAuthenticationHeader