apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-stg.yml: |
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: prometheus, health, info  # prometheus 엔드포인트 노출 (필수)
      endpoint:
        prometheus:
          enabled: true  # prometheus 엔드포인트 활성화 (필수)
        health:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true  # prometheus 메트릭 export 활성화 (필수)
    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: coubee-be-user 
                  uri: http://coubee-be-user-service:8080
                  predicates:
                    - Path=/api/user/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-store
                  uri: http://coubee-be-store-service:8080
                  predicates:
                    - Path=/api/store/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-product
                  uri: http://coubee-be-product-service:8080
                  predicates:
                    - Path=/api/product/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-order
                  uri: http://coubee-be-order-service:8080
                  predicates:
                    - Path=/api/order/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-notification
                  uri: http://coubee-be-notification-service:8080
                  predicates:
                    - Path=/api/notification/**
                  filters:
                    - addAuthenticationHeader