apiVersion: v1
kind: Service
metadata:
  name: coubee-be-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: coubee-be-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
