apiVersion: v1
kind: Service
metadata:
  name: coubee-be-gateway-nodeport
spec:
  type: NodePort # default는 ClusterIp
  selector:
    app: coubee-be-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080