apiVersion: v1
kind: Service
metadata:
  name: coubee-be-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # 여기 추가/수정
spec:
  type: LoadBalancer
  selector:
    app: coubee-be-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
