apiVersion: v1
kind: Service
metadata:
  name: coubee-be-gateway
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: coubee-be-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
